# -*- coding: utf-8 -*-
"""hash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/197zUXFa09WMtJ88EBZ0LepWjbn_lUIYv

**Importing hashing package.**
"""

import hashlib

"""**Write a program in python to generate md5 of string data.**"""

shapeai = "password"
result = hashlib.md5(shapeai.encode())
print(result.hexdigest())

"""**Write a program in python to generate hashes of string data using 3 algorithms from hashlib**

Example code generates a SHA-256 algorithm:
"""

shapeai = "password"
result = hashlib.sha256(md5.encode())
print(result.hexdigest())

"""Example code generates a SHA-1 algorithm:"""

shapeai = "password"
result = hashlib.sha1(shapeai.encode())
print(result.hexdigest())

"""Example code generates a SHA-224 algorithm:"""

shapeai = "password"
result = hashlib.sha224(shapeai.encode())
print(result.hexdigest())